<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="0" total="7" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-10T15:45:50 PST" name="Suite" finished-at="2023-11-10T15:48:04 PST" duration-ms="133562">
    <groups>
      <group name="smoke">
        <method signature="Login.login(java.lang.String,java.lang.String)[pri:0, instance:org.luma.ecommerce.testcases.Login@5f9be66c]" name="login" class="org.luma.ecommerce.testcases.Login"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2023-11-10T15:45:50 PST" name="Test" finished-at="2023-11-10T15:48:04 PST" duration-ms="133562">
      <class name="org.luma.ecommerce.testcases.E2EPurchase">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:org.luma.ecommerce.testcases.E2EPurchase@77102b91]" started-at="2023-11-10T15:47:27 PST" name="launchApplication" finished-at="2023-11-10T15:47:36 PST" duration-ms="8462" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="purchaseFlow()[pri:0, instance:org.luma.ecommerce.testcases.E2EPurchase@77102b91]" started-at="2023-11-10T15:47:36 PST" name="purchaseFlow" finished-at="2023-11-10T15:48:03 PST" duration-ms="27543" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- purchaseFlow -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.luma.ecommerce.testcases.E2EPurchase@77102b91]" started-at="2023-11-10T15:48:03 PST" name="tearDown" finished-at="2023-11-10T15:48:04 PST" duration-ms="618" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.luma.ecommerce.testcases.E2EPurchase -->
      <class name="org.luma.ecommerce.testcases.Login">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:org.luma.ecommerce.testcases.Login@5f9be66c]" started-at="2023-11-10T15:45:50 PST" name="launchApplication" finished-at="2023-11-10T15:46:01 PST" duration-ms="10437" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:org.luma.ecommerce.testcases.Login@5f9be66c]" started-at="2023-11-10T15:46:01 PST" name="login" data-provider="loginData" finished-at="2023-11-10T15:46:06 PST" duration-ms="5144" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[ashafj11@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Ashafj11!]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.luma.ecommerce.testcases.Login@5f9be66c]" started-at="2023-11-10T15:46:07 PST" name="tearDown" finished-at="2023-11-10T15:46:07 PST" duration-ms="487" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:org.luma.ecommerce.testcases.Login@5f9be66c]" started-at="2023-11-10T15:46:07 PST" name="launchApplication" finished-at="2023-11-10T15:46:16 PST" duration-ms="8838" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:org.luma.ecommerce.testcases.Login@5f9be66c]" started-at="2023-11-10T15:46:16 PST" name="login" data-provider="loginData" finished-at="2023-11-10T15:46:22 PST" duration-ms="5769" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[carlpenet123@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Ashafj11!]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.luma.ecommerce.testcases.Login@5f9be66c]" started-at="2023-11-10T15:46:22 PST" name="tearDown" finished-at="2023-11-10T15:46:22 PST" duration-ms="370" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.luma.ecommerce.testcases.Login -->
      <class name="org.luma.ecommerce.testcases.Negative_Validation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:org.luma.ecommerce.testcases.Negative_Validation@2ef14fe]" started-at="2023-11-10T15:46:22 PST" name="launchApplication" finished-at="2023-11-10T15:46:32 PST" duration-ms="9883" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginNegative_Validation()[pri:0, instance:org.luma.ecommerce.testcases.Negative_Validation@2ef14fe]" started-at="2023-11-10T15:46:32 PST" name="loginNegative_Validation" finished-at="2023-11-10T15:46:39 PST" duration-ms="6343" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.] but found [The account sign-in was incorrect or you account is disabled temporarily. Please wait and try again later.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.] but found [The account sign-in was incorrect or you account is disabled temporarily. Please wait and try again later.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at org.luma.ecommerce.testcases.Negative_Validation.loginNegative_Validation(Negative_Validation.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginNegative_Validation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.luma.ecommerce.testcases.Negative_Validation@2ef14fe]" started-at="2023-11-10T15:46:39 PST" name="tearDown" finished-at="2023-11-10T15:46:39 PST" duration-ms="328" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:org.luma.ecommerce.testcases.Negative_Validation@2ef14fe]" started-at="2023-11-10T15:46:39 PST" name="launchApplication" finished-at="2023-11-10T15:46:48 PST" duration-ms="9134" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginNegative_Validation()[pri:0, instance:org.luma.ecommerce.testcases.Negative_Validation@2ef14fe]" started-at="2023-11-10T15:46:48 PST" name="loginNegative_Validation" finished-at="2023-11-10T15:46:55 PST" duration-ms="6962" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.] but found [The account sign-in was incorrect or you account is disabled temporarily. Please wait and try again later.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.] but found [The account sign-in was incorrect or you account is disabled temporarily. Please wait and try again later.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at org.luma.ecommerce.testcases.Negative_Validation.loginNegative_Validation(Negative_Validation.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginNegative_Validation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.luma.ecommerce.testcases.Negative_Validation@2ef14fe]" started-at="2023-11-10T15:46:55 PST" name="tearDown" finished-at="2023-11-10T15:46:56 PST" duration-ms="418" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:org.luma.ecommerce.testcases.Negative_Validation@2ef14fe]" started-at="2023-11-10T15:46:56 PST" name="launchApplication" finished-at="2023-11-10T15:47:05 PST" duration-ms="9007" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginNegative_Validation()[pri:0, instance:org.luma.ecommerce.testcases.Negative_Validation@2ef14fe]" started-at="2023-11-10T15:47:05 PST" name="loginNegative_Validation" finished-at="2023-11-10T15:47:10 PST" duration-ms="5722" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.] but found [The account sign-in was incorrect or you account is disabled temporarily. Please wait and try again later.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.] but found [The account sign-in was incorrect or you account is disabled temporarily. Please wait and try again later.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at org.luma.ecommerce.testcases.Negative_Validation.loginNegative_Validation(Negative_Validation.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginNegative_Validation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.luma.ecommerce.testcases.Negative_Validation@2ef14fe]" started-at="2023-11-10T15:47:10 PST" name="tearDown" finished-at="2023-11-10T15:47:11 PST" duration-ms="429" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:org.luma.ecommerce.testcases.Negative_Validation@2ef14fe]" started-at="2023-11-10T15:47:11 PST" name="launchApplication" finished-at="2023-11-10T15:47:21 PST" duration-ms="10073" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginNegative_Validation()[pri:0, instance:org.luma.ecommerce.testcases.Negative_Validation@2ef14fe]" started-at="2023-11-10T15:47:21 PST" name="loginNegative_Validation" finished-at="2023-11-10T15:47:27 PST" duration-ms="5740" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.] but found [The account sign-in was incorrect or you account is disabled temporarily. Please wait and try again later.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.] but found [The account sign-in was incorrect or you account is disabled temporarily. Please wait and try again later.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at org.luma.ecommerce.testcases.Negative_Validation.loginNegative_Validation(Negative_Validation.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginNegative_Validation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.luma.ecommerce.testcases.Negative_Validation@2ef14fe]" started-at="2023-11-10T15:47:27 PST" name="tearDown" finished-at="2023-11-10T15:47:27 PST" duration-ms="356" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.luma.ecommerce.testcases.Negative_Validation -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
