<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-SVQG98V" failures="1" tests="4" name="org.luma.ecommerce.testcases.Negative_Validation" time="64.395" errors="0" timestamp="2023-11-10T15:48:05 PST" skipped="3">
  <testcase classname="org.luma.ecommerce.testcases.Negative_Validation" name="loginNegative_Validation" time="16.655">
    <skipped/>
  </testcase> <!-- loginNegative_Validation -->
  <system-out/>
  <testcase classname="org.luma.ecommerce.testcases.Negative_Validation" name="loginNegative_Validation" time="17.453">
    <skipped/>
  </testcase> <!-- loginNegative_Validation -->
  <system-out/>
  <testcase classname="org.luma.ecommerce.testcases.Negative_Validation" name="loginNegative_Validation" time="15.184">
    <skipped/>
  </testcase> <!-- loginNegative_Validation -->
  <system-out/>
  <testcase classname="org.luma.ecommerce.testcases.Negative_Validation" name="loginNegative_Validation" time="15.103">
    <failure message="expected [The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.] but found [The account sign-in was incorrect or you account is disabled temporarily. Please wait and try again later.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.] but found [The account sign-in was incorrect or you account is disabled temporarily. Please wait and try again later.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at org.luma.ecommerce.testcases.Negative_Validation.loginNegative_Validation(Negative_Validation.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginNegative_Validation -->
  <system-out/>
</testsuite> <!-- org.luma.ecommerce.testcases.Negative_Validation -->
